[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Jacopo Farina", email = "jacopo1.farina@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
